B28 g31 100 vs
alevgn/Cloud-Project pull request #15
Opened 2023-03-11 17:12 UTC by VeraS26

Please review!

Thank you!

2023-03-11 19:39 UTC, alevgn requested changes
Veronica, could you please delete the VS tag inside your CukesRunner and re-push your codes?

2023-03-11 21:42 UTC, untuzina approved these changes
Veronica, looks good, just remove the tag from CukesRunner file...)

2023-03-13 15:28 UTC, Alexa3462 approved these changes

2023-03-13 15:31 UTC, Mariagirbu approved these changes
good job

2023-03-13 15:35 UTC, merged