Nurseda's Commit
alevgn/Cloud-Project pull request #2
Opened 2023-03-08 23:51 UTC by nurseda916

Please review

2023-03-09 14:21 UTC, farukgoc commented on src/test/java/com/cloud/runners/CukesRunner.java
> +public class CukesRunner {};
The semicolon should be removed I guess

2023-03-09 14:46 UTC, farukgoc approved these changes
Impressive job @nurseda916. Bravo

2023-03-09 16:25 UTC, Micovs commented on src/test/java/com/cloud/runners/CukesRunner.java
> +public class CukesRunner {};
yes, looks like it. The tag should be "" since its going to the master. Also I recommend to all of us to do rebase locally before pushing. I know Omer updated the tag to " ", but here is showing change from alev to nurseda, meaning this is an old branch. Rebasing should solve issues like this. Looks great overall !!

2023-03-09 16:25 UTC, Micovs approved these changes

2023-03-09 23:25 UTC, alevgn commented
> Please review

2023-03-09 23:27 UTC, alevgn requested changes
Nurseda, it looks good. Could you just delete the tags in CukesRunner and re-push it? 
Thank you!

2023-03-10 02:41 UTC, nurseda916 commented
I deleted the semi colon and the tag. thank you

2023-03-10 04:36 UTC, untuzina commented
Good job, Nurseda!

2023-03-10 04:53 UTC, untuzina approved these changes

2023-03-11 16:15 UTC, alevgn approved these changes
Looks good Nurseda!

2023-03-11 17:48 UTC, merged