User story B28G31-101-MG is ready
alevgn/Cloud-Project pull request #6
Opened 2023-03-09 20:25 UTC by Mariagirbu

Team can you verify me? And write a message?

2023-03-09 23:36 UTC, alevgn requested changes
Maria, looks good! Could you just delete the tag name inside the CukesRunner and re-push the codes?

2023-03-10 04:34 UTC, untuzina commented
Good job, Maria!

2023-03-10 04:54 UTC, untuzina approved these changes

2023-03-10 15:58 UTC, nurseda916 approved these changes
it 's  good to go Maria, Good Job!

2023-03-11 16:19 UTC, alevgn approved these changes

2023-03-12 22:44 UTC, merged